openapi: 3.0.3
info:
  title: Game Logic Service API
  version: 1.0.0

servers:
  - url: http://localhost:3003

paths:
  /games/{matchId}:
    get:
      summary: Get game state for a match
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: matchId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current game board state
          content:
            application/json:
              schema:
                type: object
                properties:
                  matchId: { type: string }
                  board:
                    type: array
                    items:
                      type: array
                      items: { type: string }
                  currentTurn:
                    type: string
                  winner:
                    type: string
                    nullable: true
        '404':
          description: Game not found

  /games/{matchId}/move:
    post:
      summary: Submit a move for a game
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: matchId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [x, y]
              properties:
                x: { type: integer }
                y: { type: integer }
      responses:
        '200':
          description: Move accepted
        '400':
          description: Invalid move
        '403':
          description: Not your turn
        '404':
          description: Game not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
