openapi: 3.0.3
info:
  title: Matchmaking Service API
  version: 1.0.0

servers:
  - url: http://localhost:3002

paths:
  /queue/join:
    post:
      summary: Join the matchmaking queue
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Player added to queue
        '409':
          description: Already in queue

  /queue/status:
    get:
      summary: Check matchmaking status
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Queue position or match found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [waiting, matched]
                  matchId:
                    type: string
                    nullable: true

  /matches/{matchId}:
    get:
      summary: Get details of a created match
      security:
        - bearerAuth: []
      parameters:
        - name: matchId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Match info
          content:
            application/json:
              schema:
                type: object
                properties:
                  matchId: { type: string }
                  players:
                    type: array
                    items:
                      type: string
        '404':
          description: Match not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
